server:
  port: 30000
  error:
    include-message: always

spring:
  # 分布式限流的Redis连接
  redis:
    host: localhost
    port: 6379
  cloud:
    # Nacos配置项
    nacos:
      discovery:
        server-addr: localhost:8848,localhost:8948
        heart-beat-interval: 5000
        heart-beat-timeout: 15000
        cluster-name: Cluster-A
        namespace: dev
        group: myGroup
        register-enabled: true
        watch:
          enabled: true
        watch-delay: 30000
    gateway:
      discovery:
        locator:
          # 创建默认路由，以"/服务名称/接口地址"的格式规则进行转发
          # Nacos服务名称本来就是小写，但Eureka默认大写
          lower-case-service-id: true
          enabled: true
#      routes:
#        - id: id-0012
#          uri: lb://coupon-customer-serv
#          predicates:
#            - Path=/whatever/**
#          filters:
#            - StripPrefix=1
      # 跨域配置
      globalcors:
        cors-configurations:
          # 匹配所有请求路径
          '[/**]':
            # 授信地址列表
            allowed-origins:
              - "http://localhost:10000"
              - "https://www.baidu.com"
            # cookie, authorization认证信息
            expose-headers: "*"
            allowed-methods: "*"
            allow-credentials: true
            allowed-headers: "*"
            # 浏览器缓存时间
            max-age: 1000
#        add-to-simple-url-handler-mapping: true
  sleuth:
    sampler:
      probability: 1
      rate: 1000

  zipkin:
    sender:
      type: rabbit
    rabbitmq:
      addresses: 127.0.0.1:5672
      queue: zipkin

# Gateway 网关的 actuator endpoiont 进行 CRUD。
# Gateway 组件内定义了一套内置的 actuator endpoints，
# 当满足下面两个条件时，我们就可以借助 actuator 提供的能力对路由表进行修改了。
# 1.项目中存在 spring-boot-starter-actuator 依赖项；
# 2.Gateway 组件的 actuator endpoint 已对外开放。
# actuator 方案尽管实现了动态路由管理，但这些动态路由只保存在了应用的上下文中，一重启就没了
management:
  endpoints:
    web:
      exposure:
        include: "*"


#logging:
#  level: debug